# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main


stages:
- stage: Build
jobs:
- job:BuildJob
pool:
vmImage: 'windows-latest'
steps:
- task: UseDotNet@2
inputs: 
packageType: 'sdk'
version: '6.x'
- script: dotnet build
displayName: 'Build Project'

- stage: Deploy
dependsOn: Build
jobs:
- job: DeployJob
pool:
vmImage: 'windows-latest'
steps:
- scripts: echo "Deploying application"

